name: PHPUnit test

on:
  workflow_call:

jobs:
  phpunit-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4,]
        library:
          - { laravel: ^11.0 }
          - { laravel: ^12.0 }
        exclude:
          - { php: 8.4, library: { laravel: ^11.0 } }

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, zip, xml

    - name: Laravel Install
      run: |
        composer require --dev "laravel/framework:${{ matrix.library.laravel }}"

    - name: Run PHPUnit Test
      run: |
        ./vendor/bin/phpunit tests/Unit/
