name: PHPUnit test

on:
  workflow_dispatch:
  pull_request:
    branches: [
      main
    ]
    paths:
      - '.github/workflows/phpunit.yml'
      - 'config/**'
      - 'src/**'
      - 'tests/**'
jobs:
  phpunit-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - php: 8.2
            laravel: '^11.0'
            testbench: '^9.0'
          - php: 8.3
            laravel: '^11.0'
            testbench: '^9.0'
          - php: 8.4
            laravel: '^12.0'
            testbench: '^10.0'

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, zip, xml

    - name: Composer install base
      run: composer install --no-interaction --prefer-dist --no-progress

    - name: Switch Laravel/Testbench versions
      run: |
        composer require --dev "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-update
        composer update --with-all-dependencies --no-interaction --prefer-dist --no-progress

    - name: Run PHPUnit Test
      run: ./vendor/bin/phpunit tests/Unit/
